Algoritmo "EXERCICIO DE PAGAMENTO"



Var

    Nome : caractere
    ValorHora,Jornada,Salario :  real


Inicio

      Escreva("Digite o nome do funcionario: ")
      Leia(Nome)
      Escreval
      Escreva("Digite o valor por hora: ")
      Leia(ValorHora)
      Escreval
      Escreva("Digite as horas trabalhadas: ")
      Leia(Jornada)
      Escreval
      Salario <- ValorHora*Jornada
      Escreval("Valor de salario a ser pago é R$",Salario:8:2)


Fimalgoritmo