Algoritmo "EXERCICIO DE NOTA"


Var

   nota1,nota2,notaF : real


Inicio

      Escreva("Digite a primeira nota: ")
      Leia(nota1)
      escreval
      Escreva("Digite a segunda nota: ")
      Leia(nota2)
      escreval
      notaF <- (nota1+nota2)
      Escreval("Nota Final = ",notaF:4:1)
      escreval
      se(notaF >= 60) entao
        Escreva("APROVADO")
      senao
        Escreva("Reprovado")
      fimse
      escreval
      
Fimalgoritmo