Algoritmo "EXERCICIO DOS MULTIPLOS"

 //Fazer um programa para ler dois números inteiros, e dizer se um número
 // é múltiplo do outro. Os números podem ser digitados em qualquer ordem.


Var

 x,y : inteiro


Inicio

 escreva("Digite o primeiro valor: ")
 leia(x)
 escreval
 escreva("Digite o segundo valor: ")
 leia(y)
 escreval

 se(x%y=0)ou(y%x=0)entao
   escreva("São multiplos")
 senao
   escreva("Não são multiplos")
 fimse
 escreval



Fimalgoritmo