Algoritmo "EXERCICIO DE GLICOSE"



Var

 glicose : real


Inicio

      Escreva("Digite a medida da glicose: ")
      leia(glicose)
      escreval

      se(glicose<=100) entao
        Escreva("Classificacao: normal")
      senao
        se((glicose>100)e(glicose<=140)) entao
           Escreva("Classificacao: elevado")
        senao
           escreva("Classificacao: diabetes")

        fimse
      fimse

      escreval
Fimalgoritmo